apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-depl
  namespace: sumin # CHANGE_ME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway-container
          image: <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/apigateway:latest # CHANGE_ME
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  namespace: sumin # CHANGE_ME
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: apigateway
